import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { getLogsRoot } from '$lib/server/settings';
import fs from 'fs';
import path from 'path';

/**
 * Derive the next sequential folder name for a given project.
 * Scans existing dirs for a leading number prefix and increments.
 *
 * Examples:
 *   (empty dir)         → "01. My Feature"
 *   ["01. Init"]        → "02. Fix Login"
 *   ["01. A", "03. B"]  → "04. New Thing"   (uses max, not count)
 */
function buildFolderName(projectLogsDir: string, title: string): string {
	let nextNum = 1;

	if (fs.existsSync(projectLogsDir)) {
		const nums = fs
			.readdirSync(projectLogsDir, { withFileTypes: true })
			.filter((e) => e.isDirectory())
			.map((e) => {
				const m = e.name.match(/^(\d+)\./);
				return m ? parseInt(m[1], 10) : 0;
			})
			.filter((n) => n > 0);

		if (nums.length > 0) {
			nextNum = Math.max(...nums) + 1;
		}
	}

	const paddedNum = String(nextNum).padStart(2, '0');

	// Strip characters that are illegal on Windows/macOS/Linux filesystems
	const safeTitle =
		title
			.replace(/[<>:"/\\|?*\x00-\x1f]/g, '')
			.replace(/\s+/g, ' ')
			.trim()
			.slice(0, 80) || 'untitled';

	return `${paddedNum}. ${safeTitle}`;
}

export const POST: RequestHandler = async ({ request }) => {
	try {
		const { task, projectPath } = await request.json();

		if (!projectPath || !fs.existsSync(projectPath)) {
			return json({ success: false, error: 'Valid project path is required' }, { status: 400 });
		}

		const logsRoot = getLogsRoot();
		const projectName = path.basename(projectPath);
		const projectLogsDir = path.join(logsRoot, projectName);

		// ── Folder name: "01. TITLE" ──────────────────────────────────
		const folderName = buildFolderName(projectLogsDir, task.title);
		const targetDir = path.join(projectLogsDir, folderName);
		const sourceFilesDir = path.join(targetDir, 'files');

		if (!fs.existsSync(sourceFilesDir)) {
			fs.mkdirSync(sourceFilesDir, { recursive: true });
		}

		// ── Always named readme.md ────────────────────────────────────
		const filePath = path.join(targetDir, 'readme.md');

		const content = `
# ${task.description || task.title}
**Date:** ${new Date(task.createdAt).toLocaleString()}
**Project:** ${projectPath}
**Category:** ${task.title}

## Summary
${task.description || 'No description provided.'}

## Detail Code (Internal Notes)
${task.notes || 'No extra notes.'}

## Impacted Files
${task.files.length > 0 ? task.files.map((f: string) => `- ${f}`).join('\n') : 'No files listed.'}

## Modified Functions
${task.functions.length > 0 ? task.functions.map((f: string) => `- ${f}()`).join('\n') : 'No functions listed.'}

${
	task.fileDiffs
		? `## Code Diff Details\n${Object.entries(task.fileDiffs)
				.map(([file, diff]) => `### ${file}\n\`\`\`diff\n${diff}\n\`\`\``)
				.join('\n\n')}`
		: ''
}

---
*Generated by ohmycode Daily Worker Log*
`.trim();

		fs.writeFileSync(filePath, content, 'utf8');

		// ── Copy impacted source files into files/ ────────────────────
		const copiedFiles: string[] = [];
		if (task.files && task.files.length > 0) {
			for (const relativeFile of task.files) {
				const srcPath = path.resolve(projectPath, relativeFile);
				if (fs.existsSync(srcPath)) {
					const destPath = path.join(sourceFilesDir, relativeFile);
					const destSubDir = path.dirname(destPath);
					if (!fs.existsSync(destSubDir)) {
						fs.mkdirSync(destSubDir, { recursive: true });
					}
					try {
						fs.copyFileSync(srcPath, destPath);
						copiedFiles.push(relativeFile);
					} catch (e) {
						console.error(`Failed to copy file ${relativeFile}:`, e);
					}
				}
			}
		}

		return json({
			success: true,
			folderName,
			filePath,
			centralDir: targetDir,
			copiedCount: copiedFiles.length
		});
	} catch (error) {
		console.error('Save Log Error:', error);
		return json({ success: false, error: (error as Error).message }, { status: 500 });
	}
};
