import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import fs from 'fs';
import path from 'path';
import os from 'os';

export const POST: RequestHandler = async ({ request }) => {
	try {
		const { task, projectPath } = await request.json();

		if (!projectPath || !fs.existsSync(projectPath)) {
			return json({ success: false, error: 'Valid project path is required' }, { status: 400 });
		}

		// Centralized storage in User's home directory
		const homeDir = os.homedir();
		const appDataRoot = path.join(homeDir, '.ohmycode');
		const logsRoot = path.join(appDataRoot, 'logs');

		const projectName = path.basename(projectPath);
		
		const date = new Date(task.createdAt);
		const year = date.getFullYear();
		const month = String(date.getMonth() + 1).padStart(2, '0');
		const day = String(date.getDate()).padStart(2, '0');
		const dateFolderName = `${year}${month}${day}`;
		
		const targetDir = path.join(logsRoot, projectName, dateFolderName);
		const sourceFilesDir = path.join(targetDir, 'files');

		if (!fs.existsSync(sourceFilesDir)) {
			fs.mkdirSync(sourceFilesDir, { recursive: true });
		}

		// Clean filename from title
		const safeTitle = task.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
		const fileName = `${safeTitle}_${task.id.slice(0, 8)}.md`;
		const filePath = path.join(targetDir, fileName);

		// 1. Save Markdown Report
		const content = `
# Duty Log: ${task.description || task.title}
**Date:** ${new Date(task.createdAt).toLocaleString()}
**Project Path:** ${projectPath}
**Category:** ${task.title}

## Summary
${task.description || 'No description provided.'}

## Detail Code (Internal Notes)
${task.notes || 'No extra notes.'}

## Impacted Files
${task.files.length > 0 ? task.files.map(f => `- ${f}`).join('\n') : 'No files listed.'}

## Modified Functions
${task.functions.length > 0 ? task.functions.map(f => `- ${f}()`).join('\n') : 'No functions listed.'}

---
*Generated by ohmycode Daily Worker Log*
`.trim();

		fs.writeFileSync(filePath, content, 'utf8');

		// 2. Copy the actual files into the centralized folder
		const copiedFiles: string[] = [];
		if (task.files && task.files.length > 0) {
			for (const relativeFile of task.files) {
				const srcPath = path.resolve(projectPath, relativeFile);
				
				if (fs.existsSync(srcPath)) {
					// We want to maintain some structure if it's deep in src/
					// e.g. src/lib/utils.ts -> files/src/lib/utils.ts
					const destPath = path.join(sourceFilesDir, relativeFile);
					const destSubDir = path.dirname(destPath);

					if (!fs.existsSync(destSubDir)) {
						fs.mkdirSync(destSubDir, { recursive: true });
					}

					try {
						fs.copyFileSync(srcPath, destPath);
						copiedFiles.push(relativeFile);
					} catch (e) {
						console.error(`Failed to copy file ${relativeFile}:`, e);
					}
				}
			}
		}

		return json({ 
			success: true, 
			filePath,
			centralDir: targetDir,
			copiedCount: copiedFiles.length
		});
	} catch (error) {
		console.error('Save Log Error:', error);
		return json({ success: false, error: (error as Error).message }, { status: 500 });
	}
};
